// This file was automatically generated by "pack"

#pragma once

#include <stdlib.h>

#if defined(__GNUC__)
#  pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wunused-variable"
#endif

#ifdef __cplusplus
extern "C" {
#endif

extern const char metal_kernels[];
static const size_t metal_kernels_size_uncompressed = 473526;
static const size_t metal_kernels_size_compressed = 57414;

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__)
#  pragma GCC diagnostic pop
#endif

