/*
    src/llvm_core.cpp -- Low-level interface to LLVM driver API

    Copyright (c) 2021 Wenzel Jakob <wenzel.jakob@epfl.ch>

    All rights reserved. Use of this source code is governed by a BSD-style
    license that can be found in the LICENSE file.
*/

#if defined(_WIN32)
#  include <windows.h>
#else
#  include <dlfcn.h>
#  include <sys/mman.h>
#endif

#include "llvm.h"
#include "llvm_api.h"
#include "llvm_memmgr.h"
#include "internal.h"
#include "log.h"
#include "var.h"
#include "eval.h"
#include "profile.h"

static bool jitc_llvm_init_attempted  = false;
static bool jitc_llvm_init_success    = false;

/// String describing the LLVM target
char *jitc_llvm_target_triple = nullptr;

/// Target CPU string used by the LLVM backend
char *jitc_llvm_target_cpu = nullptr;

/// Target feature string used by the LLVM backend
char *jitc_llvm_target_features = nullptr;

/// Vector width of code generated by the LLVM backend
uint32_t jitc_llvm_vector_width = 0;
uint32_t jitc_llvm_max_align = 0;

// Strings related to the vector width, used by template engine

/// The literal one, for different variable types
char **jitc_llvm_ones_str = nullptr;

/// All bits set, for different variable types
char **jitc_llvm_ones_bit_str = nullptr;

/// <i32 0, i32 1, ... > (up to the current vector width)
char *jitc_llvm_u32_arange_str = nullptr;

/// <i32 width, i32 width, ... > (up to the current vector width)
char *jitc_llvm_u32_width_str = nullptr;

/// Current top-level task in the task queue
Task *jitc_task = nullptr;

/// Number of work items per block handed to nanothread
uint32_t jitc_llvm_block_size = 16384;

/// Various hardware capabilities
bool jitc_llvm_has_avx = false;
bool jitc_llvm_has_avx512 = false;
bool jitc_llvm_has_neon = false;

void jitc_llvm_update_strings();

bool jitc_llvm_init() {
    if (jitc_llvm_init_attempted)
        return jitc_llvm_init_success;
    jitc_llvm_init_attempted = true;

    if (!jitc_llvm_api_init()) {
        jitc_log(Warn, "jitc_llvm_init(): LLVM API initialization failed ..");
        return false;
    }

    if (!jitc_llvm_api_has_core()) {
        jitc_log(Warn, "jit_llvm_init(): detected LLVM version lacks core API "
                       "used by Dr.Jit, shutting down LLVM backend ..");
        jitc_llvm_api_shutdown();
        return false;
    }

    if (!jitc_llvm_api_has_pb_new()) {
        jitc_log(Warn, "jit_llvm_init(): detected LLVM version lacks pass "
                       "manager API used by Dr.Jit, shutting down LLVM backend ..");
        jitc_llvm_api_shutdown();
        return false;
    }

    LLVMInitializeDrJitTargetInfo();
    LLVMInitializeDrJitTarget();
    LLVMInitializeDrJitTargetMC();
    LLVMInitializeDrJitAsmPrinter();

    jitc_llvm_target_triple = LLVMGetDefaultTargetTriple();
    jitc_llvm_target_cpu = LLVMGetHostCPUName();
    jitc_llvm_target_features = LLVMGetHostCPUFeatures();

#if !defined(__aarch64__)
    if (!strstr(jitc_llvm_target_features, "+fma")) {
        jitc_log(Warn, "jit_llvm_init(): your CPU does not support the `fma` "
                       "instruction set, shutting down the LLVM "
                       "backend...");
        jitc_llvm_shutdown();
        return false;
    }
#endif

    jitc_llvm_vector_width = 1;

    if (strstr(jitc_llvm_target_features, "+sse4.2"))
        jitc_llvm_vector_width = 4;
    if (strstr(jitc_llvm_target_features, "+avx")) {
        jitc_llvm_vector_width = 8;
        jitc_llvm_has_avx = true;
    }
    if (strstr(jitc_llvm_target_features, "+avx512vl")) {
        jitc_llvm_vector_width = 16;
        jitc_llvm_has_avx512 = true;
    }
    if (strstr(jitc_llvm_target_features, "+neon")) {
        jitc_llvm_vector_width = 4;
        jitc_llvm_has_neon = true;
    }

#if defined(__APPLE__) && defined(__aarch64__)
    jitc_llvm_vector_width = 4;
    LLVMDisposeMessage(jitc_llvm_target_cpu);
    const char *machine_name = "apple-a14";
    if (jitc_llvm_version_major > 15)
        machine_name = "apple-m1";
    jitc_llvm_target_cpu = LLVMCreateMessage(machine_name);
#endif

    jitc_llvm_init_success = jitc_llvm_vector_width > 1;
    jitc_llvm_max_align = jitc_llvm_vector_width * 4;

    if (!jitc_llvm_init_success) {
        jitc_log(Warn,
                 "jit_llvm_init(): no suitable vector ISA found, shutting "
                 "down LLVM backend..");
        jitc_llvm_shutdown();
    }

    if (!jitc_llvm_api_has_orcv2() || !jitc_llvm_orcv2_init()) {
        jitc_log(Warn, "jit_llvm_init(): ORCv2 could not be initialized, "
                       "shutting down LLVM backend..");
        jitc_llvm_shutdown();
        return false;
    }

    if (jitc_llvm_version_major < 16) {
        jitc_log(Warn,
                 "jit_llvm_init(): the located LLVM version (%i) is too old. "
                 "The Dr.Jit LLVM backend requires LLVM 16 or newer, shutting "
                 "down LLVM backend..",
                 jitc_llvm_version_major);
        jitc_llvm_shutdown();
        return false;
    }

    jitc_llvm_update_strings();

    char major_str[11] = "?", minor_str[11] = "?", patch_str[11] = "?";

    if (jitc_llvm_version_major >= 0)
        snprintf(major_str, sizeof(major_str), "%i", jitc_llvm_version_major);
    if (jitc_llvm_version_minor >= 0)
        snprintf(minor_str, sizeof(minor_str), "%i", jitc_llvm_version_minor);
    if (jitc_llvm_version_patch >= 0)
        snprintf(patch_str, sizeof(patch_str), "%i", jitc_llvm_version_patch);

    jitc_log(Info,
             "jit_llvm_init(): found LLVM %s.%s.%s, target=%s, cpu=%s, width=%u.",
             major_str, minor_str, patch_str,
             jitc_llvm_target_triple, jitc_llvm_target_cpu,
             jitc_llvm_vector_width);

    return jitc_llvm_init_success;
}

void jitc_llvm_shutdown() {
    if (!jitc_llvm_init_success)
        return;

    jitc_log(Info, "jit_llvm_shutdown()");

    jitc_unit_cache_flush((int) JitBackend::LLVM);
    jitc_llvm_orcv2_shutdown();

    LLVMDisposeMessage(jitc_llvm_target_triple);
    LLVMDisposeMessage(jitc_llvm_target_cpu);
    LLVMDisposeMessage(jitc_llvm_target_features);

    jitc_llvm_target_cpu = nullptr;
    jitc_llvm_target_features = nullptr;
    jitc_llvm_vector_width = 0;

    if (jitc_llvm_ones_str) {
        for (uint32_t i = 0; i < (uint32_t) VarType::Count; ++i)
            free(jitc_llvm_ones_str[i]);
        free(jitc_llvm_ones_str);
    }
    jitc_llvm_ones_str = nullptr;
    if (jitc_llvm_ones_bit_str) {
        for (uint32_t i = 0; i < (uint32_t) VarType::Count; ++i)
            free(jitc_llvm_ones_bit_str[i]);
        free(jitc_llvm_ones_bit_str);
    }
    jitc_llvm_ones_bit_str = nullptr;
    free(jitc_llvm_u32_arange_str);
    jitc_llvm_u32_arange_str = nullptr;
    free(jitc_llvm_u32_width_str);
    jitc_llvm_u32_width_str = nullptr;

    jitc_llvm_init_success = false;
    jitc_llvm_init_attempted = false;

    jitc_llvm_api_shutdown();
}

void jitc_llvm_update_strings() {
    StringBuffer buf;
    uint32_t width = jitc_llvm_vector_width;

    buf.clear();
    if (jitc_llvm_ones_str) {
        for (uint32_t i = 0; i < (uint32_t) VarType::Count; ++i)
            free(jitc_llvm_ones_str[i]);
        free(jitc_llvm_ones_str);
    }
    if (jitc_llvm_ones_bit_str) {
        for (uint32_t i = 0; i < (uint32_t) VarType::Count; ++i)
            free(jitc_llvm_ones_bit_str[i]);
        free(jitc_llvm_ones_bit_str);
    }

    jitc_llvm_ones_str =
        (char **) malloc(sizeof(char *) * (uint32_t) VarType::Count);
    jitc_llvm_ones_bit_str =
        (char **) malloc(sizeof(char *) * (uint32_t) VarType::Count);

    for (uint32_t i = 0; i < (uint32_t) VarType::Count; ++i) {
        VarType vt = (VarType) i;

        buf.clear();
        buf.put('<');
        for (uint32_t j = 0; j < width; ++j) {
            buf.put(type_name_llvm[i], strlen(type_name_llvm[i]));
            buf.put(' ');

            if (vt == VarType::Float16 || vt == VarType::Float32 ||
                     vt == VarType::Float64){
                buf.put("1.0");
            } else {
                buf.put("1");
            }

            if (j + 1 < width)
                buf.put(", ");
        }
        buf.put('>');
        jitc_llvm_ones_str[i] = strdup(buf.get());

        buf.clear();
        buf.put('<');
        for (uint32_t j = 0; j < width; ++j) {
            buf.put(type_name_llvm[i], strlen(type_name_llvm[i]));
            buf.put(' ');

            if (vt == VarType::Bool)
                buf.put('1');
            else if (vt == VarType::Float16 || vt == VarType::Float32 ||
                     vt == VarType::Float64){
                buf.put("0x");
                for (uint32_t k = 0; k < 16; ++k)
                    buf.put(k < 2 * type_size[i] ? 'F' : '0');
            } else {
                buf.put("-1");
            }

            if (j + 1 < width)
                buf.put(", ");
        }
        buf.put('>');
        jitc_llvm_ones_bit_str[i] = strdup(buf.get());
    }

    buf.clear();
    buf.put('<');
    for (uint32_t j = 0; j < width; ++j) {
        buf.put("i32 ");
        buf.put_u32(j);
        if (j + 1 < width)
            buf.put(", ");
    }
    buf.put('>');

    free(jitc_llvm_u32_arange_str);
    jitc_llvm_u32_arange_str = strdup(buf.get());

    buf.clear();
    buf.put('<');
    for (uint32_t j = 0; j < width; ++j) {
        buf.put("i32 ");
        buf.put_u32(width);
        if (j + 1 < width)
            buf.put(", ");
    }
    buf.put('>');

    free(jitc_llvm_u32_width_str);
    jitc_llvm_u32_width_str = strdup(buf.get());
}

void jitc_llvm_set_target(const char *target_cpu,
                          const char *target_features,
                          uint32_t vector_width) {
    if (!jitc_llvm_init_success)
        return;

    if (jitc_llvm_target_cpu)
        LLVMDisposeMessage(jitc_llvm_target_cpu);

    if (jitc_llvm_target_features) {
        LLVMDisposeMessage(jitc_llvm_target_features);
        jitc_llvm_target_features = nullptr;
    }

    jitc_llvm_vector_width = vector_width;
    jitc_llvm_target_cpu = LLVMCreateMessage((char *) target_cpu);
    if (target_features)
        jitc_llvm_target_features = LLVMCreateMessage((char *) target_features);

    jitc_llvm_update_strings();
}

// ============================================================================
//  Per-unit kernel compilation
// ============================================================================

/// A compiled unit is an immutable, executable, position-independent image
/// shared by every kernel that links the unit. The unit cache stores it as
/// { ptr[0] = image, size = image size, value = entry point offset }.

/// Release a mapping created by jitc_llvm_map_image()
static void jitc_llvm_unmap_image(void *image, size_t size) {
#if !defined(_WIN32)
    if (munmap(image, size) == -1)
        jitc_fail("jit_llvm_unmap_image(): munmap() failed!");
#else
    (void) size;
    if (VirtualFree(image, 0, MEM_RELEASE) == 0)
        jitc_fail("jit_llvm_unmap_image(): VirtualFree() failed!");
#endif
}

static void jitc_llvm_unit_release(UnitArtifact &a) {
    jitc_llvm_unmap_image(a.ptr[0], a.size);
}

/// Copy a finished image into a fresh executable mapping. Images are PIC and
/// GOT-free, so internal references survive the relocation.
static void *jitc_llvm_map_image(const uint8_t *data, size_t size) {
#if !defined(_WIN32)
    void *ptr = mmap(nullptr, size, PROT_READ | PROT_WRITE,
                     MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (ptr == MAP_FAILED)
        jitc_fail("jit_llvm_compile(): could not mmap() memory: %s",
                  strerror(errno));
    memcpy(ptr, data, size);
    if (mprotect(ptr, size, PROT_READ | PROT_EXEC) == -1)
        jitc_fail("jit_llvm_compile(): mprotect() failed: %s", strerror(errno));
#else
    void *ptr = VirtualAlloc(nullptr, size, MEM_RESERVE | MEM_COMMIT,
                             PAGE_READWRITE);
    if (!ptr)
        jitc_fail("jit_llvm_compile(): could not VirtualAlloc() memory: %u",
                  GetLastError());
    memcpy(ptr, data, size);
    DWORD unused;
    if (VirtualProtect(ptr, size, PAGE_EXECUTE_READ, &unused) == 0)
        jitc_fail("jit_llvm_compile(): VirtualProtect() failed: %u",
                  GetLastError());
#endif
    return ptr;
}

/// Fold the target and toolchain version into a disk-cache key: unit images
/// are specific to both
static XXH128_hash_t jitc_llvm_disk_key(XXH128_hash_t hash) {
    XXH3_state_t xs;
    XXH3_128bits_reset(&xs);
    XXH3_128bits_update(&xs, &hash, sizeof(XXH128_hash_t));
    XXH3_128bits_update(&xs, jitc_llvm_target_triple,
                        strlen(jitc_llvm_target_triple));
    XXH3_128bits_update(&xs, jitc_llvm_target_cpu,
                        strlen(jitc_llvm_target_cpu));
    if (jitc_llvm_target_features)
        XXH3_128bits_update(&xs, jitc_llvm_target_features,
                            strlen(jitc_llvm_target_features));
    int version[3] = { jitc_llvm_version_major, jitc_llvm_version_minor,
                       jitc_llvm_version_patch };
    XXH3_128bits_update(&xs, version, sizeof(version));
    return XXH3_128bits_digest(&xs);
}

struct LLVMCompileJob : UnitCompileJob {
    XXH128_hash_t disk_key;   // target/toolchain-salted unit hash
    UnitArtifact artifact { };
    bool hit = false;         // served by the in-memory unit cache
    bool from_disk = false;   // image came from a disk entry
};

/// Compile one unit into a fresh executable image (runs on a worker thread)
static void jitc_llvm_compile_unit(LLVMCompileJob &job) {
    LLVMCompiler *c = jitc_llvm_compiler_acquire();
    jitc_llvm_memmgr_prepare(c->memmgr, job.source_size);

    LLVMMemoryBufferRef llvm_buf = LLVMCreateMemoryBufferWithMemoryRange(
        job.source, job.source_size, job.symbol, 0);
    if (unlikely(!llvm_buf))
        jitc_fail("jit_llvm_compile(): could not create memory buffer!");

    // 'llvm_buf' is consumed by this function.
    LLVMModuleRef llvm_module = nullptr;
    char *error = nullptr;
    LLVMParseIRInContext(c->context, llvm_buf, &llvm_module, &error);
    if (unlikely(error))
        jitc_fail("jit_llvm_compile(): parsing failed. Please see the LLVM "
                  "IR and error message below:\n\n%s\n\n%s",
                  job.source, error);
    LLVMDisposeMessage(error);

    // Check that the unit IR is valid
    bool status = LLVMVerifyModule(llvm_module, LLVMReturnStatusAction, &error);
    if (unlikely(status))
        jitc_fail("jit_llvm_compile(): module could not be verified! Please "
                  "see the LLVM IR and error message below:\n\n%s\n\n%s",
                  job.source, error);
    LLVMDisposeMessage(error);

    // Optimization pipeline. Loop unrolling and (re-)vectorization are
    // disabled: Dr.Jit programs are already vectorized, and unrolling would
    // only enlarge the generated code.
    LLVMPassBuilderOptionsRef pb_opt = LLVMCreatePassBuilderOptions();
    LLVMPassBuilderOptionsSetLoopUnrolling(pb_opt, 0);
    LLVMPassBuilderOptionsSetLoopVectorization(pb_opt, 0);
    LLVMPassBuilderOptionsSetSLPVectorization(pb_opt, 0);
    LLVMErrorRef error_ref =
        LLVMRunPasses(llvm_module, "default<O2>", c->tm, pb_opt);
    if (error_ref)
        jitc_fail("jit_llvm_compile(): failed to run optimization passes: %s!",
                  LLVMGetErrorMessage(error_ref));
    LLVMDisposePassBuilderOptions(pb_opt);

    // Code generation via LLJIT, into the instance's bump allocator
    LLVMErrorRef err = LLVMOrcJITDylibClear(c->dylib);
    if (err)
        jitc_fail("jit_llvm_compile(): could not clear dylib: %s",
                  LLVMGetErrorMessage(err));

    LLVMOrcThreadSafeContextRef ts_ctx = LLVMOrcCreateNewThreadSafeContext();
    LLVMOrcThreadSafeModuleRef ts_mod =
        LLVMOrcCreateNewThreadSafeModule(llvm_module, ts_ctx);
    LLVMOrcDisposeThreadSafeContext(ts_ctx);

    err = LLVMOrcLLJITAddLLVMIRModule(c->lljit, c->dylib, ts_mod);
    if (err)
        jitc_fail("jit_llvm_compile(): could not add module: %s",
                  LLVMGetErrorMessage(err));

    LLVMOrcExecutorAddress addr = 0;
    err = LLVMOrcLLJITLookup(c->lljit, &addr, job.symbol);
    if (err)
        jitc_fail("jit_llvm_compile(): could not resolve symbol \"%s\": %s",
                  job.symbol, LLVMGetErrorMessage(err));

    if (c->memmgr.got)
        jitc_fail(
            "jit_llvm_compile(): a global offset table was generated by LLVM, "
            "which typically means that a compiler intrinsic was not supported "
            "by the target architecture. DrJit cannot handle this case "
            "and will terminate the application now. For reference, the "
            "following kernel code was responsible for this problem:\n\n%s",
            job.source);

    job.artifact.size = (uint32_t) c->memmgr.offset;
    job.artifact.value =
        (uint64_t) ((uint8_t *) (uintptr_t) addr - c->memmgr.data);
    job.artifact.ptr[0] = jitc_llvm_map_image(c->memmgr.data, c->memmgr.offset);

    jitc_llvm_compiler_release(c);
}

static ProfilerRegion profiler_region_llvm_compile("jit_llvm_compile");

bool jitc_llvm_kernel_compile(Kernel &kernel) {
    ProfilerPhase phase(profiler_region_llvm_compile);

    size_t n_units = 1 + callable_units.size(),
           image_bytes = 0;

    std::vector<LLVMCompileJob> jobs(n_units);
    std::vector<uint32_t> misses;

    for (size_t i = 0; i < n_units; ++i) {
        LLVMCompileJob &job = jobs[i];
        jitc_unit_job_init(i, job);

        if (jitc_unit_cache_lookup(JitBackend::LLVM, job.unit_hash, 0,
                                   job.artifact)) {
            job.hit = true;
            continue;
        }

        // The source size doubles as the disk collision check
        job.disk_key = jitc_llvm_disk_key(job.unit_hash);
        misses.push_back((uint32_t) i);
    }

    // Release the lock while compiling. The job sources stay valid
    // throughout (see UnitCompileJob in unit.h)
    if (!misses.empty()) {
        unlock_guard guard(state.lock);

        // Probe the disk cache; its payload is {u32 entry offset, image}
        std::vector<uint32_t> pending;
        std::vector<uint8_t> data;
        for (uint32_t i : misses) {
            LLVMCompileJob &job = jobs[i];

            if (jitc_cache_blob_load("llvm", job.disk_key,
                                     (uint32_t) job.source_size, data) &&
                data.size() > sizeof(uint32_t)) {
                uint32_t entry_offset;
                memcpy(&entry_offset, data.data(), sizeof(uint32_t));
                uint32_t size = (uint32_t) (data.size() - sizeof(uint32_t));
                if (entry_offset < size) {
                    job.artifact.size = size;
                    job.artifact.value = entry_offset;
                    job.artifact.ptr[0] = jitc_llvm_map_image(
                        data.data() + sizeof(uint32_t), size);
                    job.from_disk = true;
                    continue;
                }
            }

            pending.push_back(i);
        }

        if (!pending.empty()) {
            jitc_unit_compile_parallel(
                pending, [&](uint32_t i) { return jobs[i].source_size; },
                [&](uint32_t i) { jitc_llvm_compile_unit(jobs[i]); });

            // Persist the new images
            for (uint32_t i : pending) {
                const LLVMCompileJob &job = jobs[i];
                uint32_t entry_offset = (uint32_t) job.artifact.value;
                data.resize(sizeof(uint32_t) + job.artifact.size);
                memcpy(data.data(), &entry_offset, sizeof(uint32_t));
                memcpy(data.data() + sizeof(uint32_t), job.artifact.ptr[0],
                       job.artifact.size);
                jitc_cache_blob_store("llvm", job.disk_key,
                                      (uint32_t) job.source_size,
                                      data.data(), data.size(),
                                      /* replace = */ false);
            }
        }

        // Publish the new artifacts; the cache pins the images
        for (uint32_t i : misses)
            jitc_unit_cache_insert(JitBackend::LLVM, jobs[i].unit_hash, 0,
                                   jobs[i].artifact, jitc_llvm_unit_release);
    }

    // Link: the kernel references the entry points of its units. 'reloc[0]'
    // is the kernel entry; the array doubles as the callable table that the
    // launch binds to a reserved kernel parameter.
    kernel.llvm.reloc = (void **) malloc_check(sizeof(void *) * n_units);

    bool all_cached = true;
    for (size_t i = 0; i < n_units; ++i) {
        const LLVMCompileJob &job = jobs[i];
        kernel.llvm.reloc[i] =
            (uint8_t *) job.artifact.ptr[0] + job.artifact.value;
        image_bytes += job.artifact.size;
        all_cached &= job.hit || job.from_disk;
    }
    kernel.size = (uint32_t) image_bytes;

#if defined(DRJIT_ENABLE_ITTNOTIFY)
    kernel.llvm.itt = __itt_string_handle_create(kernel_name);
#endif

    return all_cached;
}

std::pair<uint32_t, uint32_t> jitc_llvm_expand_replication_factor(uint32_t size, uint32_t tsize) {
    uint32_t workers = pool_size();
    // 1 cache line per worker for scalar targets, otherwise be a bit more
    // reasonable
    uint32_t replication_per_worker = size == 1u ? (64u / tsize) : 1u;

    return std::pair(workers, replication_per_worker);
}
