/*
    src/llvm_core.cpp -- Low-level interface to LLVM driver API

    Copyright (c) 2021 Wenzel Jakob <wenzel.jakob@epfl.ch>

    All rights reserved. Use of this source code is governed by a BSD-style
    license that can be found in the LICENSE file.
*/

#include "llvm.h"
#include "llvm_api.h"
#include "llvm_orcv2.h"
#include "internal.h"
#include "log.h"
#include "var.h"
#include "eval.h"
#include "profile.h"

static bool jitc_llvm_init_attempted  = false;
static bool jitc_llvm_init_success    = false;

/// String describing the LLVM target
char *jitc_llvm_target_triple = nullptr;

/// Target CPU string used by the LLVM backend
char *jitc_llvm_target_cpu = nullptr;

/// Target feature string used by the LLVM backend
char *jitc_llvm_target_features = nullptr;

/// Vector width of code generated by the LLVM backend
uint32_t jitc_llvm_vector_width = 0;
uint32_t jitc_llvm_max_align = 0;

// Strings related to the vector width, used by template engine

/// The literal one, for different variable types
char **jitc_llvm_ones_str = nullptr;

/// All bits set, for different variable types
char **jitc_llvm_ones_bit_str = nullptr;

/// <i32 0, i32 1, ... > (up to the current vector width)
char *jitc_llvm_u32_arange_str = nullptr;

/// <i32 width, i32 width, ... > (up to the current vector width)
char *jitc_llvm_u32_width_str = nullptr;

/// Current top-level task in the task queue
Task *jitc_task = nullptr;

/// Number of work items per block handed to nanothread
uint32_t jitc_llvm_block_size = 16384;

/// Various hardware capabilities
bool jitc_llvm_has_avx = false;
bool jitc_llvm_has_avx512 = false;
bool jitc_llvm_has_neon = false;

void jitc_llvm_update_strings();

bool jitc_llvm_init() {
    if (jitc_llvm_init_attempted)
        return jitc_llvm_init_success;
    jitc_llvm_init_attempted = true;

    if (!jitc_llvm_api_init()) {
        jitc_log(Warn, "jitc_llvm_init(): LLVM API initialization failed ..");
        return false;
    }

    if (jitc_llvm_version_major < 18) {
        jitc_log(Warn,
                 "jit_llvm_init(): the located LLVM version (%i) is too old. "
                 "The Dr.Jit LLVM backend requires LLVM 18 or newer, shutting "
                 "down LLVM backend..",
                 jitc_llvm_version_major);
        jitc_llvm_api_shutdown();
        return false;
    }

    if (!jitc_llvm_api_has_core()) {
        jitc_log(Warn, "jit_llvm_init(): detected LLVM version lacks core API "
                       "used by Dr.Jit, shutting down LLVM backend ..");
        jitc_llvm_api_shutdown();
        return false;
    }

    if (!jitc_llvm_api_has_pb_new()) {
        jitc_log(Warn, "jit_llvm_init(): detected LLVM version lacks pass "
                       "manager API used by Dr.Jit, shutting down LLVM backend ..");
        jitc_llvm_api_shutdown();
        return false;
    }

    LLVMInitializeDrJitTargetInfo();
    LLVMInitializeDrJitTarget();
    LLVMInitializeDrJitTargetMC();
    LLVMInitializeDrJitAsmPrinter();

    jitc_llvm_target_triple = LLVMGetDefaultTargetTriple();
    jitc_llvm_target_cpu = LLVMGetHostCPUName();
    jitc_llvm_target_features = LLVMGetHostCPUFeatures();

#if !defined(__aarch64__)
    if (!strstr(jitc_llvm_target_features, "+fma")) {
        jitc_log(Warn, "jit_llvm_init(): your CPU does not support the `fma` "
                       "instruction set, shutting down the LLVM "
                       "backend...");
        jitc_llvm_shutdown();
        return false;
    }
#endif

    jitc_llvm_vector_width = 1;

    if (strstr(jitc_llvm_target_features, "+sse4.2"))
        jitc_llvm_vector_width = 4;
    if (strstr(jitc_llvm_target_features, "+avx")) {
        jitc_llvm_vector_width = 8;
        jitc_llvm_has_avx = true;
    }
    if (strstr(jitc_llvm_target_features, "+avx512vl")) {
        jitc_llvm_vector_width = 16;
        jitc_llvm_has_avx512 = true;
    }
    if (strstr(jitc_llvm_target_features, "+neon")) {
        jitc_llvm_vector_width = 4;
        jitc_llvm_has_neon = true;
    }

#if defined(__APPLE__) && defined(__aarch64__)
    jitc_llvm_vector_width = 4;
    LLVMDisposeMessage(jitc_llvm_target_cpu);
    jitc_llvm_target_cpu = LLVMCreateMessage("apple-m1");
#endif

    jitc_llvm_init_success = jitc_llvm_vector_width > 1;
    jitc_llvm_max_align = jitc_llvm_vector_width * 4;

    if (!jitc_llvm_init_success) {
        jitc_log(Warn,
                 "jit_llvm_init(): no suitable vector ISA found, shutting "
                 "down LLVM backend..");
        jitc_llvm_shutdown();
    }

    if (!jitc_llvm_api_has_orcv2() || !jitc_llvm_orcv2_init()) {
        jitc_log(Warn, "jit_llvm_init(): ORCv2 could not be initialized, "
                       "shutting down LLVM backend..");
        jitc_llvm_shutdown();
        return false;
    }

    jitc_llvm_update_strings();

    char major_str[11] = "?", minor_str[11] = "?", patch_str[11] = "?";

    if (jitc_llvm_version_major >= 0)
        snprintf(major_str, sizeof(major_str), "%i", jitc_llvm_version_major);
    if (jitc_llvm_version_minor >= 0)
        snprintf(minor_str, sizeof(minor_str), "%i", jitc_llvm_version_minor);
    if (jitc_llvm_version_patch >= 0)
        snprintf(patch_str, sizeof(patch_str), "%i", jitc_llvm_version_patch);

    jitc_log(Info,
             "jit_llvm_init(): found LLVM %s.%s.%s, target=%s, cpu=%s, width=%u.",
             major_str, minor_str, patch_str,
             jitc_llvm_target_triple, jitc_llvm_target_cpu,
             jitc_llvm_vector_width);

    return jitc_llvm_init_success;
}

void jitc_llvm_shutdown() {
    if (!jitc_llvm_init_success)
        return;

    jitc_log(Info, "jit_llvm_shutdown()");

    jitc_unit_cache_flush((int) JitBackend::LLVM);
    jitc_llvm_orcv2_shutdown();

    LLVMDisposeMessage(jitc_llvm_target_triple);
    LLVMDisposeMessage(jitc_llvm_target_cpu);
    LLVMDisposeMessage(jitc_llvm_target_features);

    jitc_llvm_target_cpu = nullptr;
    jitc_llvm_target_features = nullptr;
    jitc_llvm_vector_width = 0;

    if (jitc_llvm_ones_str) {
        for (uint32_t i = 0; i < (uint32_t) VarType::Count; ++i)
            free(jitc_llvm_ones_str[i]);
        free(jitc_llvm_ones_str);
    }
    jitc_llvm_ones_str = nullptr;
    if (jitc_llvm_ones_bit_str) {
        for (uint32_t i = 0; i < (uint32_t) VarType::Count; ++i)
            free(jitc_llvm_ones_bit_str[i]);
        free(jitc_llvm_ones_bit_str);
    }
    jitc_llvm_ones_bit_str = nullptr;
    free(jitc_llvm_u32_arange_str);
    jitc_llvm_u32_arange_str = nullptr;
    free(jitc_llvm_u32_width_str);
    jitc_llvm_u32_width_str = nullptr;

    jitc_llvm_init_success = false;
    jitc_llvm_init_attempted = false;

    jitc_llvm_api_shutdown();
}

void jitc_llvm_update_strings() {
    StringBuffer buf;
    uint32_t width = jitc_llvm_vector_width;

    buf.clear();
    if (jitc_llvm_ones_str) {
        for (uint32_t i = 0; i < (uint32_t) VarType::Count; ++i)
            free(jitc_llvm_ones_str[i]);
        free(jitc_llvm_ones_str);
    }
    if (jitc_llvm_ones_bit_str) {
        for (uint32_t i = 0; i < (uint32_t) VarType::Count; ++i)
            free(jitc_llvm_ones_bit_str[i]);
        free(jitc_llvm_ones_bit_str);
    }

    jitc_llvm_ones_str =
        (char **) malloc(sizeof(char *) * (uint32_t) VarType::Count);
    jitc_llvm_ones_bit_str =
        (char **) malloc(sizeof(char *) * (uint32_t) VarType::Count);

    for (uint32_t i = 0; i < (uint32_t) VarType::Count; ++i) {
        VarType vt = (VarType) i;

        buf.clear();
        buf.put('<');
        for (uint32_t j = 0; j < width; ++j) {
            buf.put(type_name_llvm[i], strlen(type_name_llvm[i]));
            buf.put(' ');

            if (vt == VarType::Float16 || vt == VarType::Float32 ||
                     vt == VarType::Float64){
                buf.put("1.0");
            } else {
                buf.put("1");
            }

            if (j + 1 < width)
                buf.put(", ");
        }
        buf.put('>');
        jitc_llvm_ones_str[i] = strdup(buf.get());

        buf.clear();
        buf.put('<');
        for (uint32_t j = 0; j < width; ++j) {
            buf.put(type_name_llvm[i], strlen(type_name_llvm[i]));
            buf.put(' ');

            if (vt == VarType::Bool)
                buf.put('1');
            else if (vt == VarType::Float16 || vt == VarType::Float32 ||
                     vt == VarType::Float64){
                buf.put("0x");
                for (uint32_t k = 0; k < 16; ++k)
                    buf.put(k < 2 * type_size[i] ? 'F' : '0');
            } else {
                buf.put("-1");
            }

            if (j + 1 < width)
                buf.put(", ");
        }
        buf.put('>');
        jitc_llvm_ones_bit_str[i] = strdup(buf.get());
    }

    buf.clear();
    buf.put('<');
    for (uint32_t j = 0; j < width; ++j) {
        buf.put("i32 ");
        buf.put_u32(j);
        if (j + 1 < width)
            buf.put(", ");
    }
    buf.put('>');

    free(jitc_llvm_u32_arange_str);
    jitc_llvm_u32_arange_str = strdup(buf.get());

    buf.clear();
    buf.put('<');
    for (uint32_t j = 0; j < width; ++j) {
        buf.put("i32 ");
        buf.put_u32(width);
        if (j + 1 < width)
            buf.put(", ");
    }
    buf.put('>');

    free(jitc_llvm_u32_width_str);
    jitc_llvm_u32_width_str = strdup(buf.get());
}

void jitc_llvm_set_target(const char *target_cpu,
                          const char *target_features,
                          uint32_t vector_width) {
    if (!jitc_llvm_init_success)
        return;

    if (jitc_llvm_target_cpu)
        LLVMDisposeMessage(jitc_llvm_target_cpu);

    if (jitc_llvm_target_features) {
        LLVMDisposeMessage(jitc_llvm_target_features);
        jitc_llvm_target_features = nullptr;
    }

    jitc_llvm_vector_width = vector_width;
    jitc_llvm_target_cpu = LLVMCreateMessage((char *) target_cpu);
    if (target_features)
        jitc_llvm_target_features = LLVMCreateMessage((char *) target_features);

    jitc_llvm_update_strings();

    // Pooled target machines describe the previous target
    jitc_llvm_compiler_pool_clear();
}

// ============================================================================
//  Per-unit kernel compilation
// ============================================================================

/// Each unit compiles into a relocatable object file, which the disk cache
/// stores verbatim. Linking it into the process produces the artifact that
/// every kernel using the unit shares (see jitc_llvm_link() for its layout).

static void jitc_llvm_unit_release(UnitArtifact &a) {
    jitc_llvm_unlink(a);
}

/// Fold the target, toolchain version, and cache version into a disk-cache
/// key: unit objects are specific to all three
static XXH128_hash_t jitc_llvm_disk_key(XXH128_hash_t hash) {
    // A seeded reset consults the previous state, so it must be initialized
    XXH3_state_t xs;
    XXH3_INITSTATE(&xs);
    XXH3_128bits_reset_withSeed(&xs, DRJIT_CACHE_VERSION);
    XXH3_128bits_update(&xs, &hash, sizeof(XXH128_hash_t));
    XXH3_128bits_update(&xs, jitc_llvm_target_triple,
                        strlen(jitc_llvm_target_triple));
    XXH3_128bits_update(&xs, jitc_llvm_target_cpu,
                        strlen(jitc_llvm_target_cpu));
    if (jitc_llvm_target_features)
        XXH3_128bits_update(&xs, jitc_llvm_target_features,
                            strlen(jitc_llvm_target_features));
    int version[3] = { jitc_llvm_version_major, jitc_llvm_version_minor,
                       jitc_llvm_version_patch };
    XXH3_128bits_update(&xs, version, sizeof(version));
    return XXH3_128bits_digest(&xs);
}

struct LLVMCompileJob : UnitCompileJob {
    XXH128_hash_t disk_key;      // target/toolchain-salted unit hash
    UnitArtifact artifact { };
    std::vector<uint8_t> object; // relocatable object file
    bool hit = false;            // served by the in-memory unit cache
    bool from_disk = false;      // object came from a disk entry
};

/// Compile one unit into a relocatable object file (runs on a worker thread)
static void jitc_llvm_compile_unit(LLVMCompileJob &job) {
    LLVMCompiler *c = jitc_llvm_compiler_acquire();

    LLVMMemoryBufferRef llvm_buf = LLVMCreateMemoryBufferWithMemoryRange(
        job.source, job.source_size, job.symbol, 0);
    if (unlikely(!llvm_buf))
        jitc_fail("jit_llvm_compile(): could not create memory buffer!");

    // 'llvm_buf' is consumed by this function.
    LLVMModuleRef llvm_module = nullptr;
    char *error = nullptr;
    LLVMParseIRInContext(c->context, llvm_buf, &llvm_module, &error);
    if (unlikely(error))
        jitc_fail("jit_llvm_compile(): parsing failed. Please see the LLVM "
                  "IR and error message below:\n\n%s\n\n%s",
                  job.source, error);
    LLVMDisposeMessage(error);

    // Check that the unit IR is valid
    bool status = LLVMVerifyModule(llvm_module, LLVMReturnStatusAction, &error);
    if (unlikely(status))
        jitc_fail("jit_llvm_compile(): module could not be verified! Please "
                  "see the LLVM IR and error message below:\n\n%s\n\n%s",
                  job.source, error);
    LLVMDisposeMessage(error);

    // Optimization pipeline. Loop unrolling and (re-)vectorization are
    // disabled: Dr.Jit programs are already vectorized, and unrolling would
    // only enlarge the generated code.
    LLVMPassBuilderOptionsRef pb_opt = LLVMCreatePassBuilderOptions();
    LLVMPassBuilderOptionsSetLoopUnrolling(pb_opt, 0);
    LLVMPassBuilderOptionsSetLoopVectorization(pb_opt, 0);
    LLVMPassBuilderOptionsSetSLPVectorization(pb_opt, 0);
    LLVMErrorRef error_ref =
        LLVMRunPasses(llvm_module, "default<O2>", c->tm, pb_opt);
    if (error_ref)
        jitc_fail("jit_llvm_compile(): failed to run optimization passes: %s!",
                  LLVMGetErrorMessage(error_ref));
    LLVMDisposePassBuilderOptions(pb_opt);

    // Code generation
    LLVMMemoryBufferRef obj_buf = nullptr;
    if (LLVMTargetMachineEmitToMemoryBuffer(c->tm, llvm_module, LLVMObjectFile,
                                            &error, &obj_buf))
        jitc_fail("jit_llvm_compile(): code generation failed. Please see "
                  "the LLVM IR and error message below:\n\n%s\n\n%s",
                  job.source, error);
    LLVMDisposeModule(llvm_module);

    const char *obj_data = LLVMGetBufferStart(obj_buf);
    job.object.assign(obj_data, obj_data + LLVMGetBufferSize(obj_buf));
    LLVMDisposeMemoryBuffer(obj_buf);

    jitc_llvm_compiler_release(c);
}

static ProfilerRegion profiler_region_llvm_compile("jit_llvm_compile");

bool jitc_llvm_kernel_compile(Kernel &kernel) {
    ProfilerPhase phase(profiler_region_llvm_compile);

    size_t n_units = 1 + callable_units.size(),
           object_bytes = 0;

    std::vector<LLVMCompileJob> jobs(n_units);
    std::vector<uint32_t> misses;

    for (size_t i = 0; i < n_units; ++i) {
        LLVMCompileJob &job = jobs[i];
        jitc_unit_job_init(i, job);

        if (jitc_unit_cache_lookup(JitBackend::LLVM, job.unit_hash, 0,
                                   job.artifact)) {
            job.hit = true;
            continue;
        }

        job.disk_key = jitc_llvm_disk_key(job.unit_hash);
        misses.push_back((uint32_t) i);
    }

    // Release the lock while compiling. The job sources stay valid
    // throughout (see UnitCompileJob in unit.h)
    if (!misses.empty()) {
        unlock_guard guard(state.lock);

        // Probe the disk cache for the object files
        for (uint32_t i : misses) {
            LLVMCompileJob &job = jobs[i];
            job.from_disk =
                jitc_cache_blob_load(CacheKind::Object, job.disk_key,
                                     job.object) &&
                !job.object.empty();
        }

        // Compile the remaining units, then link every miss into the process
        // and hand its object file to a detached store. Linking is cheap
        // compared to compilation, so issue those jobs last.
        jitc_unit_compile_parallel(
            misses,
            [&](uint32_t i) {
                return jobs[i].from_disk ? (size_t) 0 : jobs[i].source_size;
            },
            [&](uint32_t i) {
                LLVMCompileJob &job = jobs[i];
                if (!job.from_disk)
                    jitc_llvm_compile_unit(job);
                jitc_llvm_link(job.symbol, job.object.data(), job.object.size(),
                               job.source, job.artifact);
                if (!job.from_disk)
                    jitc_cache_blob_store_async(CacheKind::Object, job.disk_key,
                                                std::move(job.object));
            });

        // Publish the new artifacts; the cache pins the linked units
        for (uint32_t i : misses)
            jitc_unit_cache_insert(JitBackend::LLVM, jobs[i].unit_hash, 0,
                                   jobs[i].artifact, jitc_llvm_unit_release);
    }

    // The kernel references the entry points of its units. 'reloc[0]' is the
    // kernel entry; the array doubles as the callable table that the launch
    // binds to a reserved kernel parameter.
    kernel.llvm.reloc = (void **) malloc_check(sizeof(void *) * n_units);

    bool all_cached = true;
    for (size_t i = 0; i < n_units; ++i) {
        const LLVMCompileJob &job = jobs[i];
        kernel.llvm.reloc[i] = (void *) (uintptr_t) job.artifact.value;
        object_bytes += job.artifact.size;
        all_cached &= job.hit || job.from_disk;
    }
    kernel.size = (uint32_t) object_bytes;

#if defined(DRJIT_ENABLE_ITTNOTIFY)
    kernel.llvm.itt = __itt_string_handle_create(kernel_name);
#endif

    return all_cached;
}

std::pair<uint32_t, uint32_t> jitc_llvm_expand_replication_factor(uint32_t size, uint32_t tsize) {
    uint32_t workers = pool_size();
    // 1 cache line per worker for scalar targets, otherwise be a bit more
    // reasonable
    uint32_t replication_per_worker = size == 1u ? (64u / tsize) : 1u;

    return std::pair(workers, replication_per_worker);
}
