# bin2c.cmake -- embed binary file(s) into a generated C source as byte arrays.
#
# Used by Dr.Jit-Core (compressed PTX kernels, the Metal kernel metallib) and
# reusable by downstream projects. Two modes:
#
#   * Included as a module: defines drjit_embed_binary(), which registers a
#     build-time add_custom_command. The generated .c is a proper build artifact
#     that depends on its input binary, so editing the binary regenerates only
#     the .c on the next build -- no reconfigure, parallel-safe.
#
#   * Run via `cmake -P bin2c.cmake` (script mode): performs the conversion,
#     driven by the BIN2C_* variables the custom command passes through -D.

if (CMAKE_SCRIPT_MODE_FILE)
    # ---------------------------- script mode ----------------------------
    # Lists are passed with '|' separators ('-D VAR=a;b' would be split into
    # separate arguments by the command invocation).
    string(REPLACE "|" ";" _symbols "${BIN2C_SYMBOLS}")
    string(REPLACE "|" ";" _inputs  "${BIN2C_INPUTS}")

    set(_out "// Auto-generated by bin2c.cmake -- do not edit.\n\n")
    if (BIN2C_SIZE)
        string(APPEND _out "#include <stddef.h>\n\n") # for size_t
    endif()
    if (BIN2C_HEADER)
        string(APPEND _out "#include \"${BIN2C_HEADER}\"\n\n")
    endif()

    list(LENGTH _symbols _n)
    math(EXPR _last "${_n} - 1")
    foreach (_i RANGE ${_last})
        list(GET _symbols ${_i} _sym)
        list(GET _inputs  ${_i} _in)

        file(READ "${_in}" _hex HEX)
        string(LENGTH "${_hex}" _hexlen)
        math(EXPR _len "${_hexlen} / 2")
        string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
        string(REGEX REPLACE "((0x..,){16})" "\\1\n    " _bytes "${_bytes}")

        string(APPEND _out "const ${BIN2C_TYPE} ${_sym}[] = {\n    ${_bytes}\n};\n")
        if (BIN2C_SIZE)
            string(APPEND _out "const size_t ${_sym}_size = ${_len};\n")
        endif()
        string(APPEND _out "\n")
    endforeach()

    file(WRITE "${BIN2C_OUTPUT}" "${_out}")
    return()
endif()

# ------------------------------ module mode ------------------------------

# Absolute path to this script, stored globally so drjit_embed_binary() can
# reach it from any directory scope (it is called from both Dr.Jit-Core and
# downstream projects). CMAKE_CURRENT_FUNCTION_LIST_DIR would be cleaner but
# requires CMake >= 3.17.
set(DRJIT_BIN2C_SCRIPT "${CMAKE_CURRENT_LIST_FILE}"
    CACHE INTERNAL "Path to bin2c.cmake")

# drjit_embed_binary(
#     OUTPUT  <path>          # .c file to generate (also add it to a target)
#     SYMBOLS <name> [<name>] # one or more C array identifiers
#     INPUTS  <file> [<file>] # matching binaries (same count and order)
#     [TYPE   <c-type>]       # array element type (default: "unsigned char")
#     [SIZE]                  # also emit `const size_t <name>_size`
#     [HEADER <path>]         # add `#include "<path>"` (e.g. matching decls)
# )
function(drjit_embed_binary)
    cmake_parse_arguments(PARSE_ARGV 0 ARG "SIZE" "OUTPUT;TYPE;HEADER" "SYMBOLS;INPUTS")
    if (NOT ARG_TYPE)
        set(ARG_TYPE "unsigned char")
    endif()

    string(REPLACE ";" "|" _symbols "${ARG_SYMBOLS}")
    string(REPLACE ";" "|" _inputs  "${ARG_INPUTS}")

    set(_opt "")
    if (ARG_SIZE)
        list(APPEND _opt "-DBIN2C_SIZE=ON")
    endif()
    if (ARG_HEADER)
        list(APPEND _opt "-DBIN2C_HEADER=${ARG_HEADER}")
    endif()

    add_custom_command(
        OUTPUT "${ARG_OUTPUT}"
        COMMAND ${CMAKE_COMMAND}
            "-DBIN2C_OUTPUT=${ARG_OUTPUT}"
            "-DBIN2C_SYMBOLS=${_symbols}"
            "-DBIN2C_INPUTS=${_inputs}"
            "-DBIN2C_TYPE=${ARG_TYPE}"
            ${_opt}
            -P "${DRJIT_BIN2C_SCRIPT}"
        DEPENDS ${ARG_INPUTS} "${DRJIT_BIN2C_SCRIPT}"
        COMMENT "Embedding ${ARG_SYMBOLS} -> ${ARG_OUTPUT}"
        VERBATIM
    )
endfunction()
